AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graphql-custom-authorizer

  Sample SAM Template for graphql-custom-authorizer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
    Description: environment to be configured within the .toml
  ApiKey:
    Type: String
    Default: "7ad572dc-c56c-4ed8-a891-4760ff9b636b"
    Description: Api Key as unencoded UUID for default auth and direct endpoint testing for lower envs

Resources:
  CustomAuthorizerDemoLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: custom-auth-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
  BasicGraphqlApi:
    Type: AWS::AppSync::GraphQLApi
    Properties: 
      AdditionalAuthenticationProviders: 
        - 
          AuthenticationType: AWS_LAMBDA
          LambdaAuthorizerConfig: 
            AuthorizerResultTtlInSeconds: 60
            AuthorizerUri: !Ref CustomAuthorizerDemoLambda
      AuthenticationType: API_KEY
      Name: !Sub "${stage}-graphql-custom-authorizer-api"
      Tags: 
        - 
          Key: cost-allocatable
          Value: "true"
        -
          Key: logical-resource
          Value: !Sub "${stage}-graphql-custom-authorizer"
      XrayEnabled: false
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
